### ISSUE TITLE
Need to add "restore" to notebook params

### ISSUE THREAD

**Issue by usergenic** [pytti-tools/pytti-notebook#36]
For longer video work, the "restore" feature is often necessary.  However, it appears the toggle has been pulled out of the notebook params so there's no way to restore a run without going into workhorse.py and setting restore to True.

**Comment by dmarx** [comment]
I think I removed it because it wasn't working, but I've put off looking into it for long enough. Thanks for bumping me, will look into it.

**Comment by dmarx** [comment]
just noticed you were playing with the restore feature in your fork. Still haven't actually gotten around to playing with this myself: in your experiments, did you observe that simply setting the option to "True" was sufficient to trigger the appropriate "restore" behavior? If really all that's needed is to add back a checkbox, that'd be wonderful. Were you going to turn your fork into a PR?

**Comment by usergenic** [comment]
Hey @dmarx so far setting restore to True has been sufficient at least for the Video Source case I use it for.  I think there was a comment somewhere I read that said restore relies on the backup folder.  So assuming that folder is present with contents I am guessing it works.  I'll send a PR in a minute.

**Comment by usergenic** [comment]
https://github.com/pytti-tools/pytti-core/pull/112

**Comment by usergenic** [comment]
In order to be compatible with version of notebook that doesn't provide restore as a parameter, I set the code in pytti-core to `restore = params.get('restore') or False`
