### ISSUE TITLE
Error when generate video

### ISSUE THREAD

**Issue by minhtq1207** [pytti-tools/pytti-notebook#51]
i got below error at final step to generate video 
![image](https://user-images.githubusercontent.com/7424881/175348971-009e6d7e-4481-4241-9520-e4f908ec3dd6.png)

**Comment by dmarx** [comment]
moved issue to pytti-tools/pytti-notebook since this is specific to the notebook and is completely isolated from the pytti-core library

**Comment by dmarx** [comment]
Thanks for your patience everyone, should be fixed now!

**Comment by janpilu** [comment]
> hi, just tried making a video of a new animation and got the same error. Here are the output files in the file_namespace folder ![image](https://user-images.githubusercontent.com/14015669/176883276-c7351366-a0b3-4ab4-9265-589cb45dfd5d.png) Also I was having trouble resuming the run after google colab kicked me out. It output the files as file_namespace_1(1).php instead of starting at the last frame from previous run. Not sure if that is related to this problem maybe it's having trouble reading the files in the directory or maybe something else. I'm a novice Python programmer and still learning about ML but I notice that other scripts I've played around with use Image%04d.png to name the output, I don't know though just a thought. I like the audio input setting that other notebooks don't have so I hope you/we can get it to work, thanks.

Did You manage to resolve the bug where the resume checkbox doesn't actually lead to the notebook resuming the previous run?

**Comment by paulhaskett** [comment]
@janpilu no, unfortunately I couldn't maybe open a new issue.
